name: "Python Code Quality and Lint for Home Assistant components"
description: "Supports pylint, black, mypy"
inputs:
  hass-version:
    description: "Home Assistant version"
    required: true
    default: ">=2022.3.0"
  path:
    description: "Component path"
    required: true
    default: "."
  use-pylint:
    description: "Use Pylint"
    required: false
    default: true
  use-black:
    description: "Use Black"
    required: false
    default: true
  use-mypy:
    description: "Use mypy"
    required: false
    default: true
  use-pytest:
    description: "Use pytest"
    required: false
    default: false
  extra-pylint-options:
    description: "Extra options: pylint $(extra-pylint-options) $(path)"
    required: false
    default: ""
  extra-black-options:
    description: "Extra options: black --check $(extra-black-options) $(path)"
    required: false
    default: ""
  extra-mypy-options:
    description: "Extra options: mypy $(extra-mypy-options) $(path)"
    required: false
    default: ""
  extra-pytest-options:
    description: "Extra options: pytest $(extra-pytest-options)"
    required: false
    default: ""
  use-hass-branch:
    description: "Use branch instead of version"
    required: false
    default: false

runs:
  using: "docker"
  image: "Dockerfile"
  args:
    - ${{ inputs.hass-version }}
    - ${{ inputs.path }}
    - ${{ inputs.use-pylint }}
    - ${{ inputs.use-black }}
    - ${{ inputs.use-mypy }}
    - ${{ inputs.extra-pylint-options }}
    - ${{ inputs.extra-black-options }}
    - ${{ inputs.extra-mypy-options }}
    - ${{ inputs.use-hass-branch }}
    - ${{ inputs.use-pytest }}
    - ${{ inputs.extra-pytest-options }}
branding:
  icon: "terminal"
  color: "blue"